### ISSUE TITLE
Why not reuse existing contract libraries?

### ISSUE THREAD

**Issue by boundless-forest** [sublayer-art/Sublayer_Protocol#2]
I noticed there are some libs https://github.com/sublayer-art/Sublayer_Protocol/tree/main/contracts/lib in the codebase. Why not use the existing audited contract library like OpenZeppelin? If we want this project to run long-term instead of being a toy project, we should adopt the best practices in the industry. Especially in the blockchain area, security is highly important. Utilizing those audited libs can also reduce our maintenance or audit costs in the future if there are more users.

**Comment by leo-xinwang** [comment]
Library is refactored using openzeppelin on main branch
