### ISSUE TITLE
`TO LAUNCHPAD` button no response

### ISSUE THREAD

**Issue by boundless-forest** [sublayer-art/Sublayer_Protocol#3]
![image](https://github.com/user-attachments/assets/a819a196-d091-407c-bf35-de5c75f98a2a)

It appears no response when clicking the `TO LAUNCHPAD` button. I didn't know much about the UI design about this project, but it seems weird. Maybe it should jump to somewhere?

**Comment by leo-xinwang** [comment]
This issue is the same as
https://github.com/sublayer-art/Sublayer_Protocol/issues/4
