### ISSUE TITLE
Is it possible to create a new collection?

### ISSUE THREAD

**Issue by boundless-forest** [sublayer-art/Sublayer_Protocol#4]
![image](https://github.com/user-attachments/assets/65f8528e-3672-49b9-abaa-2cdb4e276e00)

There is a default collection when you open the app. From what I understand, Sublayer aims to be an NFT marketplace, so it should support multiple collections, right?

**Comment by leo-xinwang** [comment]
Yes, multiple collections are supported. Currently new collection is created from backend.

**Comment by boundless-forest** [comment]
> Yes, multiple collections are supported. Currently new collection is created from backend.

For a market, I believe that supporting collection creation in the frontend is an essential functionality, as backend creation does not meet the actual needs.

**Comment by leo-xinwang** [comment]
Create new NFT api is available now, will get front UI updated soon
https://github.com/sublayer-art/sublayer-api/blob/main/README.md

**Comment by leo-xinwang** [comment]
Front end page is added
https://sublayer.art/launchpad

**Comment by boundless-forest** [comment]
Nice Job.
