### ISSUE TITLE
Filters in Trade seem not to work

### ISSUE THREAD

**Issue by boundless-forest** [sublayer-art/Sublayer_Protocol#5]
The filter for price and rarity seems not to function. I'm curious how to distinguish which NFT is Uncommon, Rare, or Epic; it appears there is no indication in the NFT to display the rarity.

![image](https://github.com/user-attachments/assets/405594a7-eb96-4f78-801c-0f5659115554)

**Comment by leo-xinwang** [comment]
Price filter added
rarity is not activated now and will be improved for one of a kind NFT collection
