### ISSUE TITLE
What does the `Floor` mean?

### ISSUE THREAD

**Issue by boundless-forest** [sublayer-art/Sublayer_Protocol#6]
![image](https://github.com/user-attachments/assets/1bbc8075-186d-4018-a444-9d3f66c06ae1)

What is the meaning of the Floor? If it refers to the upper price for the NFT, why can I sell the minted NFT for 5 RING?

For the second question, the Listed/Total shows there are 218 NFTs. Is there a way to display them all instead of just the listed ones?

**Comment by leo-xinwang** [comment]
Floor means the lowest price on sell, this has been fixed.
The second question is an option, however for trading market usually availble for sale are displayed.
