### ISSUE TITLE
Have to refresh the site to display the newly minted NFT.

### ISSUE THREAD

**Issue by boundless-forest** [sublayer-art/Sublayer_Protocol#7]
![image](https://github.com/user-attachments/assets/6bfc0c1f-0545-443b-b700-d121e55ba181)

The newly minted NFT requires you to refresh the entire site for it to disappear. It makes no sense in the current web design, in my opinion. It should load automatically, or at least when I switch between the MyNFTs, Listed, and Created tabs, it should disappear.

**Comment by leo-xinwang** [comment]
Auto refresh mechanism added
